---
title: "SAJA-Egypt IQVIA Monthly Report"
description: |
  This is IQVIA Monthly Analysis 
site: distill::distill_website
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```


# IQVIA Monthly Intelligent Table

```{r include=FALSE, message=FALSE, echo=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(plotly)
library(ggplot2)
library(janitor)
library(gganimate)
library(readxl)
library(dygraphs)
library(rpivotTable)
# names(dfinto)
# read the data from csv file
dfinto <- read_excel("in_to_YTD.xlsx")
```


```{r IQVIA, echo = FALSE,message=FALSE, warning=FALSE}
IQVIA <- read_excel("C:\\Users\\asahmed\\Documents\\GitHub\\R_For_Reports\\IQVIA.xlsx")
rpivotTable(IQVIA)

```

***

### Detailed Grphs

```{r echo=FALSE, warning=FALSE}
dfinto <- IQVIA %>% 
  select(everything()) %>% 
  filter(Type_Unit_Value == "LC Value" )
  

  # filter(month != c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct")) %>%
  # mutate(Value = Value/1000000)

ggplot(dfinto, aes(x = Year, y = Ammount )) +
  geom_col(na.rm = TRUE, aes(fill=Year),
             position = 'dodge')
```

```{r echo=FALSE, warning=FALSE}
dfgg1 <- dfinto %>% 
  ggplot(aes(x=Month,
         y = Ammount,
         fill=Type_Unit_Value))+
  geom_col(position = 'dodge') +
  ggtitle("in-to market sales YTD/Oct 18-21")


dfgg11 <- ggplotly(dfgg1)
dfgg11


```

```{r echo=FALSE, warning=FALSE}
dfinto_1 <- dfinto %>% 
  select(Ammount,Type_Unit_Value,Year, Month) %>% 
  mutate(Month = as.factor(Month)) %>%
  mutate(Year = as.character(Year)) %>% 
  mutate(Type = as.factor(Type_Unit_Value))
  

dygraph(dfinto_1)

```



```{r echo=FALSE, warning=FALSE}

dfgg3 <- dfinto %>% 
  ggplot(aes(x = Year,y=Ammount))+
    geom_jitter(aes(col = Type_Unit_Value))
dfgg3

dfgg3 <- dfgg3+
  transition_states(Year,transition_length = 2,
                    state_length = 0.5)+
  ease_aes()
dfgg3
```

```{r echo=FALSE, warning=FALSE}


dfgg3 <- dfinto %>% 
  ggplot(aes(x = Year,y=Ammount))+
  geom_boxplot(aes(fill = Type_Unit_Value))
dfgg3

dfgg3 <- dfgg3+
  transition_states(Year,transition_length = 2,
                    state_length = 0.5)+
  ease_aes()
dfgg3

```

